spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always

jwt:
  ttl: 2592000000
  secret: jigali
